# Generated by Django 2.2.10 on 2020-07-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Модель')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='/media/', verbose_name='Изображение')),
                ('release_date', models.DateField(blank=True, verbose_name='Дата выхода')),
                ('lte_exists', models.BooleanField(blank=True, verbose_name='lte')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
